/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package VIEW;

import CONTROLLER.PROJECTCONTROLLER;
import CONTROLLER.TASKCONTROLLER;
import MODEL.PROJECTS;
import java.awt.Color;
import java.awt.Font;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.List;
import javax.swing.DefaultListModel;

/**
 *
 * @author victo
 */
public class MAINSCREEN extends javax.swing.JFrame {

    PROJECTCONTROLLER projectController;
    TASKCONTROLLER taskController;
    
    DefaultListModel  projectModel;
    
    
    public MAINSCREEN() {
        initComponents();
        decorateTableTask();
        
        initDataController();
        initComponentsModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelemptylist = new javax.swing.JPanel();
        jLabelemptylisticon = new javax.swing.JLabel();
        jLabelemptylisttitle = new javax.swing.JLabel();
        jLabelemptylistsubtitle = new javax.swing.JLabel();
        jPaneltollbar = new javax.swing.JPanel();
        jLabeltoolbartitle = new javax.swing.JLabel();
        jLabeltoolbarsubtitle = new javax.swing.JLabel();
        jPanelprojects = new javax.swing.JPanel();
        jLabelprojectstitle = new javax.swing.JLabel();
        jLabelprojectsadd = new javax.swing.JLabel();
        jPaneltasks = new javax.swing.JPanel();
        jLabeltaskstitle = new javax.swing.JLabel();
        jLabeltasksadd = new javax.swing.JLabel();
        jPanelprojectlist = new javax.swing.JPanel();
        jScrollPaneprojects = new javax.swing.JScrollPane();
        jListprojects = new javax.swing.JList<>();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableTasks = new javax.swing.JTable();

        jPanelemptylist.setBackground(java.awt.Color.white);
        jPanelemptylist.setName("itens tarefas"); // NOI18N

        jLabelemptylisticon.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabelemptylisticon.setForeground(new java.awt.Color(0, 153, 102));
        jLabelemptylisticon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelemptylisticon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/list.png"))); // NOI18N

        jLabelemptylisttitle.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelemptylisttitle.setForeground(new java.awt.Color(0, 153, 102));
        jLabelemptylisttitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelemptylisttitle.setText("Nenhuma tarefa por aqui!!");

        jLabelemptylistsubtitle.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelemptylistsubtitle.setForeground(new java.awt.Color(153, 153, 153));
        jLabelemptylistsubtitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelemptylistsubtitle.setText("Clique no botão \"+\" para adicionar uma nova tarefa");

        javax.swing.GroupLayout jPanelemptylistLayout = new javax.swing.GroupLayout(jPanelemptylist);
        jPanelemptylist.setLayout(jPanelemptylistLayout);
        jPanelemptylistLayout.setHorizontalGroup(
            jPanelemptylistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelemptylistLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelemptylistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelemptylisticon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelemptylisttitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelemptylistsubtitle, javax.swing.GroupLayout.DEFAULT_SIZE, 363, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanelemptylistLayout.setVerticalGroup(
            jPanelemptylistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelemptylistLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelemptylisticon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelemptylisttitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelemptylistsubtitle)
                .addGap(85, 85, 85))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 600));
        setName("painel principal"); // NOI18N

        jPaneltollbar.setBackground(new java.awt.Color(0, 153, 102));
        jPaneltollbar.setName("barra principal"); // NOI18N

        jLabeltoolbartitle.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabeltoolbartitle.setForeground(new java.awt.Color(255, 255, 255));
        jLabeltoolbartitle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/caixa-de-selecao3.png"))); // NOI18N
        jLabeltoolbartitle.setText(" To.Do App");
        jLabeltoolbartitle.setName("app titulo"); // NOI18N

        jLabeltoolbarsubtitle.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabeltoolbarsubtitle.setForeground(new java.awt.Color(255, 255, 255));
        jLabeltoolbarsubtitle.setText("Anote tudo, não esqueça nada!");

        javax.swing.GroupLayout jPaneltollbarLayout = new javax.swing.GroupLayout(jPaneltollbar);
        jPaneltollbar.setLayout(jPaneltollbarLayout);
        jPaneltollbarLayout.setHorizontalGroup(
            jPaneltollbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPaneltollbarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPaneltollbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabeltoolbartitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabeltoolbarsubtitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPaneltollbarLayout.setVerticalGroup(
            jPaneltollbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPaneltollbarLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabeltoolbartitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(jLabeltoolbarsubtitle)
                .addContainerGap())
        );

        jLabeltoolbartitle.getAccessibleContext().setAccessibleDescription("");

        jPanelprojects.setBackground(new java.awt.Color(255, 255, 255));
        jPanelprojects.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanelprojects.setForeground(new java.awt.Color(255, 255, 255));
        jPanelprojects.setName("painel projetos"); // NOI18N

        jLabelprojectstitle.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelprojectstitle.setForeground(new java.awt.Color(0, 153, 102));
        jLabelprojectstitle.setText("Projetos");
        jLabelprojectstitle.setName("painel projetos"); // NOI18N

        jLabelprojectsadd.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabelprojectsadd.setForeground(new java.awt.Color(0, 153, 102));
        jLabelprojectsadd.setText("+");
        jLabelprojectsadd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelprojectsaddMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanelprojectsLayout = new javax.swing.GroupLayout(jPanelprojects);
        jPanelprojects.setLayout(jPanelprojectsLayout);
        jPanelprojectsLayout.setHorizontalGroup(
            jPanelprojectsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelprojectsLayout.createSequentialGroup()
                .addComponent(jLabelprojectstitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelprojectsadd)
                .addContainerGap())
        );
        jPanelprojectsLayout.setVerticalGroup(
            jPanelprojectsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelprojectsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelprojectsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelprojectstitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelprojectsadd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPaneltasks.setBackground(new java.awt.Color(255, 255, 255));
        jPaneltasks.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabeltaskstitle.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabeltaskstitle.setForeground(new java.awt.Color(0, 153, 102));
        jLabeltaskstitle.setText("Tarefas");
        jLabeltaskstitle.setName("painel tarefas"); // NOI18N

        jLabeltasksadd.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabeltasksadd.setForeground(new java.awt.Color(0, 153, 102));
        jLabeltasksadd.setText("+");
        jLabeltasksadd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabeltasksaddMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPaneltasksLayout = new javax.swing.GroupLayout(jPaneltasks);
        jPaneltasks.setLayout(jPaneltasksLayout);
        jPaneltasksLayout.setHorizontalGroup(
            jPaneltasksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPaneltasksLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabeltaskstitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jLabeltasksadd, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPaneltasksLayout.setVerticalGroup(
            jPaneltasksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPaneltasksLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPaneltasksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabeltaskstitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabeltasksadd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanelprojectlist.setBackground(new java.awt.Color(255, 255, 255));
        jPanelprojectlist.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jListprojects.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jListprojects.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jListprojects.setFixedCellHeight(50);
        jListprojects.setName("itens projetos"); // NOI18N
        jListprojects.setSelectionBackground(new java.awt.Color(0, 153, 102));
        jScrollPaneprojects.setViewportView(jListprojects);

        javax.swing.GroupLayout jPanelprojectlistLayout = new javax.swing.GroupLayout(jPanelprojectlist);
        jPanelprojectlist.setLayout(jPanelprojectlistLayout);
        jPanelprojectlistLayout.setHorizontalGroup(
            jPanelprojectlistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelprojectlistLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPaneprojects)
                .addContainerGap())
        );
        jPanelprojectlistLayout.setVerticalGroup(
            jPanelprojectlistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelprojectlistLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPaneprojects)
                .addContainerGap())
        );

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jTableTasks.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTableTasks.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nome", "Descrição", "Prazo", "Tarefa Concluida"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableTasks.setGridColor(java.awt.Color.white);
        jTableTasks.setRowHeight(50);
        jTableTasks.setSelectionBackground(new java.awt.Color(153, 255, 153));
        jTableTasks.setShowVerticalLines(false);
        jScrollPane1.setViewportView(jTableTasks);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 343, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPaneltollbar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanelprojects, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelprojectlist, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPaneltasks, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPaneltollbar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanelprojects, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPaneltasks, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelprojectlist, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelprojectsaddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelprojectsaddMouseClicked
        // TODO add your handling code here:
        ProjectDialogScreen projectDialogScreen = new ProjectDialogScreen(this, rootPaneCheckingEnabled);
        projectDialogScreen.setVisible(true);
        
        projectDialogScreen.addWindowListener(new WindowAdapter() {
            public void windowClosed(WindowEvent e){
                LoadProjects();
            }
            
        });
        
    }//GEN-LAST:event_jLabelprojectsaddMouseClicked

    private void jLabeltasksaddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabeltasksaddMouseClicked
        // TODO add your handling code here:
        TaskDialogScreen2 taskDialogScreen2 = new TaskDialogScreen2(this, rootPaneCheckingEnabled);
        taskDialogScreen2.setProject(null);
        taskDialogScreen2.setVisible(true);
        
    }//GEN-LAST:event_jLabeltasksaddMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Java swing".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MAINSCREEN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MAINSCREEN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MAINSCREEN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MAINSCREEN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MAINSCREEN().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelemptylisticon;
    private javax.swing.JLabel jLabelemptylistsubtitle;
    private javax.swing.JLabel jLabelemptylisttitle;
    private javax.swing.JLabel jLabelprojectsadd;
    private javax.swing.JLabel jLabelprojectstitle;
    private javax.swing.JLabel jLabeltasksadd;
    private javax.swing.JLabel jLabeltaskstitle;
    private javax.swing.JLabel jLabeltoolbarsubtitle;
    private javax.swing.JLabel jLabeltoolbartitle;
    private javax.swing.JList<String> jListprojects;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanelemptylist;
    private javax.swing.JPanel jPanelprojectlist;
    private javax.swing.JPanel jPanelprojects;
    private javax.swing.JPanel jPaneltasks;
    private javax.swing.JPanel jPaneltollbar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPaneprojects;
    private javax.swing.JTable jTableTasks;
    // End of variables declaration//GEN-END:variables

    public void decorateTableTask(){
    jTableTasks.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 14));
    jTableTasks.getTableHeader().setBackground(new Color(0,153,102));
    jTableTasks.getTableHeader().setForeground(new Color(255,255,255));
    
    jTableTasks.setAutoCreateRowSorter(true);
            
            }
    
    public void initDataController(){
        projectController = new PROJECTCONTROLLER();
        taskController = new TASKCONTROLLER();
        
        
    }
    
    public void initComponentsModel(){
        projectModel = new DefaultListModel();
        LoadProjects();
        
    }
    
    public void LoadProjects(){
        List <PROJECTS> Projects = projectController.getall();
        
        projectModel.clear();
        
        for (int i = 0; i < Projects.size(); i++){
            PROJECTS project = Projects.get(i);
            projectModel.addElement(project);
            
            
        }
        
        jListprojects.setModel(projectModel);
        
        
    }
    
    
}
