/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package VIEW;

import CONTROLLER.TASKCONTROLLER;
import MODEL.PROJECTS;
import MODEL.TASK;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author victo
 */
public class TaskDialogScreen2 extends javax.swing.JDialog {

    
    TASKCONTROLLER controller;
    PROJECTS project;
    
    public TaskDialogScreen2(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        controller = new TASKCONTROLLER();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPaneltoolbar = new javax.swing.JPanel();
        jLabeltoolbartitle = new javax.swing.JLabel();
        jLabeltoolbarsave = new javax.swing.JLabel();
        jPaneltask = new javax.swing.JPanel();
        jLabelname = new javax.swing.JLabel();
        jTextFieldname = new javax.swing.JTextField();
        jLabeldescription = new javax.swing.JLabel();
        jLabeldeadline = new javax.swing.JLabel();
        jFormattedTextFielddeadline = new javax.swing.JFormattedTextField();
        jLabelnotes = new javax.swing.JLabel();
        jScrollPanedescription = new javax.swing.JScrollPane();
        jTextAreadescription = new javax.swing.JTextArea();
        jScrollPanenotes = new javax.swing.JScrollPane();
        jTextAreanotes = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(455, 513));

        jPaneltoolbar.setBackground(new java.awt.Color(0, 153, 102));

        jLabeltoolbartitle.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabeltoolbartitle.setForeground(java.awt.Color.white);
        jLabeltoolbartitle.setText("TAREFA");

        jLabeltoolbarsave.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabeltoolbarsave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/check.png"))); // NOI18N
        jLabeltoolbarsave.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabeltoolbarsaveMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPaneltoolbarLayout = new javax.swing.GroupLayout(jPaneltoolbar);
        jPaneltoolbar.setLayout(jPaneltoolbarLayout);
        jPaneltoolbarLayout.setHorizontalGroup(
            jPaneltoolbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPaneltoolbarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabeltoolbartitle, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabeltoolbarsave, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE))
        );
        jPaneltoolbarLayout.setVerticalGroup(
            jPaneltoolbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabeltoolbartitle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabeltoolbarsave, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE)
        );

        jPaneltask.setBackground(java.awt.Color.white);

        jLabelname.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelname.setText("Nome");

        jTextFieldname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldnameActionPerformed(evt);
            }
        });

        jLabeldescription.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabeldescription.setText("Descrição");

        jLabeldeadline.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabeldeadline.setText("Prazo");

        jFormattedTextFielddeadline.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter()));

        jLabelnotes.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelnotes.setText("Notas");

        jTextAreadescription.setColumns(20);
        jTextAreadescription.setRows(5);
        jScrollPanedescription.setViewportView(jTextAreadescription);

        jTextAreanotes.setColumns(20);
        jTextAreanotes.setRows(5);
        jScrollPanenotes.setViewportView(jTextAreanotes);

        javax.swing.GroupLayout jPaneltaskLayout = new javax.swing.GroupLayout(jPaneltask);
        jPaneltask.setLayout(jPaneltaskLayout);
        jPaneltaskLayout.setHorizontalGroup(
            jPaneltaskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPaneltaskLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPaneltaskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPanenotes)
                    .addComponent(jScrollPanedescription)
                    .addComponent(jLabelname, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextFieldname, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabeldescription, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabeldeadline, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jFormattedTextFielddeadline, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPaneltaskLayout.createSequentialGroup()
                        .addComponent(jLabelnotes)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPaneltaskLayout.setVerticalGroup(
            jPaneltaskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPaneltaskLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabelname)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabeldescription)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPanedescription, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabeldeadline)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jFormattedTextFielddeadline, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelnotes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPanenotes, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPaneltoolbar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPaneltask, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPaneltoolbar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPaneltask, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldnameActionPerformed

    private void jLabeltoolbarsaveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabeltoolbarsaveMouseClicked
        // TODO add your handling code here:
        
        try {
            TASK task = new TASK();
            
            
            task.setID_PROJECT(project.getID());
            task.setNAME(jTextFieldname.getText());
            task.setDESCRIPTION(jTextAreadescription.getText());
            task.setNOTES(jTextAreanotes.getText());
            task.setIS_COMPLETED(false);
            
            SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
            Date DEADLINE = null;
            
            DEADLINE = dateFormat.parse(jFormattedTextFielddeadline.getText());
            task.setDEADLINE(DEADLINE);
            controller.Save(task);
            
            JOptionPane.showMessageDialog(rootPane, "tarefa salva com sucesso");
            
            
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e.getMessage());
        }
        this.dispose();
    }//GEN-LAST:event_jLabeltoolbarsaveMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TaskDialogScreen2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TaskDialogScreen2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TaskDialogScreen2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TaskDialogScreen2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TaskDialogScreen2 dialog = new TaskDialogScreen2(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField jFormattedTextFielddeadline;
    private javax.swing.JLabel jLabeldeadline;
    private javax.swing.JLabel jLabeldescription;
    private javax.swing.JLabel jLabelname;
    private javax.swing.JLabel jLabelnotes;
    private javax.swing.JLabel jLabeltoolbarsave;
    private javax.swing.JLabel jLabeltoolbartitle;
    private javax.swing.JPanel jPaneltask;
    private javax.swing.JPanel jPaneltoolbar;
    private javax.swing.JScrollPane jScrollPanedescription;
    private javax.swing.JScrollPane jScrollPanenotes;
    private javax.swing.JTextArea jTextAreadescription;
    private javax.swing.JTextArea jTextAreanotes;
    private javax.swing.JTextField jTextFieldname;
    // End of variables declaration//GEN-END:variables

    public void setProject(PROJECTS project) {
        this.project = project;
    }


}
